# -*- coding: utf-8 -*-
"""Reto 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LD6CtNrb5J3vkk2CLKaulk5oUolZ2IKJ

#**RETO 1: LAVADO DE ACTIVOs**
En este documento se desarrolla y analiza un modelo Naive Bayes, a traves del cual se busca fortalecer el sistema analitico de una entidad financiera para la  identiciación temprana de clientes de riesgo especificamente en el lavado de activos. De acuerdo a lo anterior se tendrán en cuenta las sigueintes variables:


**Lavado de Activos**: Nos muestra si el cliente ha sido antes identificado por lavado de activos.


**Porcentaje del crecimiento de patrimonio:** A traves del cula analizamos cambios abruptos en el patrimonio de los clientes.

**Monto Transado:** Explican la complejidad y son claves para analizar el perfil del cliente

**Ingresos y Gastos:** Estas dos variables, nos ayudan a identificar inconsistencias entre los ingresos y egresos de los clientes. Tambien ayuda a determinar el perfil del cliente de acuerdo a sus movimientos financieros.

0. Carga de Librerias
"""

import numpy as np #Numerica por excelencia
import pandas as pd #Comunicación con los archivos de excel
#Librerias especificas: Ej. Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

"""1. Cargar la base de datos"""

nxl="/content/2. LavadoActivos.xlsx"
XDB=pd.read_excel(nxl,sheet_name=0)
Xd=XDB[['ingresos_usd','gastos_usd','monto_transado_tarjetas_usd','porcentaje_crecimiento_patrimonio']]
Xd.head()
yd=XDB['lavado_activos']
yd.head()

"""2. Implementación del Modelo Naive Bayes"""

mnb=GaussianNB()
mnb.fit(Xd,yd)
u=mnb.theta_
sigma=mnb.var_;sigma=np.sqrt(sigma)
print("'ingresos_usd','gastos_usd','monto_transado_tarjetas_usd','porcentaje_crecimiento_patrimonio")
print(u)
print("Las desviaciones son")
print(sigma)

"""#**Analisis de Resultados:**
Basado en estos resultados, podemos ver una diferencia clara en los movimientos financieros de los clientes pre clasificados como alto riesgo de lavado de activos, tanto en los **ingresos** como en los **gastos**. Esto puede llevar a cuestionar la procedencia de tan alta flujo de dinero, y puede requerir al banco una mayor trazabilidad. Adicionalmente, el **monto transado en tarjetas** tambien muestra una superioridad para los clientes con perfil preclasificado como alto riesgo, lo cual es congruente con lo anterior.  

Por otro lado, **las desviaciónes**, que en la categoria de Alto Riesgo son mayores a las de bajo riesgos, nos demuestran que aquellos quienes ya han sido Pre Clasificados como alto riego, tiene una mayor volatilidad y un comportamiento mucho menos homogeneo y predecible que la clase con bajo riesgo.

3. Se procede con la evaluación del modelo.
"""

ydp=mnb.predict(Xd)
cm=confusion_matrix(yd,ydp)
print(cm)
VN=cm[0,0];FP=cm[0,1];FN=cm[1,0]; VP=cm[1,1];TDatos=len(XDB)
#1:Exactitud: Funcionamiento general del modelo
EX=((VP+VN)/TDatos)*100
print("Exactitud: ",EX)
#2: Tasa de error: Porcentaje de fallo del sistema
TEr=((FP+FN)/TDatos)*100
print("Tasa de error: ",TEr)
#3:Sensibilidad: Como se comporto con respecto a los positivos de la base de datos
Se=(VP/(VP+FN))*100
print("Sensibilidad: ",Se)
#4:Especificidad:
Es=(VN/(VN+FP))*100
print("Especificidad: ",Es)
#5. Precisión: Version de como funciona frente a los positivos solamente
Pr=(VP/(VP+FP))*100
print("Precision: ",Pr)
#6: Predicción Negativa: Funcionamiento del modelo pronosticando creditos Pre Negados
Prn=(VN/(VN+FN))*100
print("Predicción Negativa: ",Prn)

"""#**Analisis de Resultados:**
Los resultados de la matriz de confusión nos ayudan a determianr que tan bien esta el funcionamineto del sistema. De acuerdo a la primera metrica, **La Exactitud:** Con un total de 94% de exactitud, nos demuestra que en terminos generales el modelo tiene un muy buen funcionamineto, y una **tasa de error** del 5.9% lo cual es bastante bajo. **La Sensibilidad:** Nos demuestra un funcionamiento de detección del 84%, de los clientes que presentan un riesgo real de lavado de activos. **La Especificidad** nos muestra que el modelo es estrico y que logro pasar el 98% de los clientes que en realidad no presentaban ningun riesgo, ademas un 94% de **precision**, nos muestra que el sistema no esta enviando alertas innecesarias. La predicción negativa del modelo, nos confirma que es un modelo confiable con un 93%.
"""